//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNİKSERVİS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTEKNİKSERVİSEntities : DbContext
    {
        public DBTEKNİKSERVİSEntities()
            : base("name=DBTEKNİKSERVİSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblArızaDetay> tblArızaDetay { get; set; }
        public virtual DbSet<tblCari> tblCari { get; set; }
        public virtual DbSet<tblDepartman> tblDepartman { get; set; }
        public virtual DbSet<tblFaturaBilgi> tblFaturaBilgi { get; set; }
        public virtual DbSet<tblFaturaDetay> tblFaturaDetay { get; set; }
        public virtual DbSet<tblGIDER> tblGIDER { get; set; }
        public virtual DbSet<tblKategori> tblKategori { get; set; }
        public virtual DbSet<tblNotlar> tblNotlar { get; set; }
        public virtual DbSet<tblPersonel> tblPersonel { get; set; }
        public virtual DbSet<tblUrun> tblUrun { get; set; }
        public virtual DbSet<tblUrunHareket> tblUrunHareket { get; set; }
        public virtual DbSet<tblUrunKabul> tblUrunKabul { get; set; }
        public virtual DbSet<tblUrunTakip> tblUrunTakip { get; set; }
    }
}
