//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNİKSERVİS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArızaDetay
    {
        public int ARIZAID { get; set; }
        public Nullable<int> ISLEMID { get; set; }
        public string SORUN { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> ONFIYAT { get; set; }
        public Nullable<decimal> NETFIYAT { get; set; }
        public string ISLEMLER { get; set; }
    }
}
