//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNİKSERVİS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotlar
    {
        public int ID { get; set; }
        public string BASLIK { get; set; }
        public byte[] ICERIK { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
